name: "instala maven 3-9.11"
description: "instalacion despues de java"

runs:
  using: "composite"
  steps:
    - name: Descargar Maven 3.9.11
      shell: bash
      run:  |
        ACTION_ROOT="${{ github.action_path }}"
        cd "$ACTION_ROOT"

        TARGET_DIR="${{ github.workspace }}"
        tar -xzf apache-maven-3.9.11-bin.tar.gz -C "$TARGET_DIR"

    - name: Descargar Maven 3.9.11
      shell: bash
      run:  |
        cd "${{ github.workspace }}"

        MAVEN_DIR=$(ls -d apache-maven-*/ | head -n 1)

        echo "${{ github.workspace }}/${MAVEN_DIR}bin" >> $GITHUB_ENV
    
    - name: Mostrar versión de Maven instalada
      shell: bash
      run: mvn --version