name: REUSABLE

on:
  workflow_dispatch:

jobs:
  checkout-repos:
    runs-on: [self-hosted, localrunner]
    steps:

      - name: Mostrar secret
        run:  |
          echo "GH_APP_ID: ${{ secrets.GH_APP_ID }}"
          echo "GH_APP_KEY: ${{ secrets.GH_APP_KEY }}"

      - name: Generar token GitHub App
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Checkout proyecto
        uses: actions/checkout@v4
        with:
          repository: edwien-dev/fe-miapp
          ref: main
          token: ${{ steps.app-token.outputs.token }}
          path: repo_codigo

      - name: Ver repos
        run: ls -la