name: ejecuta mi action  
on:
  workflow_dispatch:
  workflow_call:

jobs:
  hola:
    runs-on: ['arc-runnerset-2025']
    steps:
      - name: ejemplo action
        uses: edwien-dev/central_devops/ac-hola@main
        with:
          nombre: jean gutierrez
        
