name: ejecuta mi action  
on:
  workflow_dispatch:
  workflow_call:

jobs:
  hola:
    runs-on: ['arc-normaliza-runner-set']
    container:
      image: node:20
    steps:
      - uses: actions/checkout@v4

      - name: Ver versión de Node y npm
        run: |
          node -v
          npm -v
      