name: ejecuta mi action  
on:
  workflow_dispatch:
  workflow_call:

jobs:
  hola:
    runs-on: ['arc-runnerset-2025']
    steps:
      - name: ejemplo action
        uses: edwien-dev/central_devops/ac-hola@main
        with:
          nombre: jean gutierrez

      - name: Verificar versión de Node.js
        run: node -v

      - name: Verificar versión de npm
        run: npm -v

      - name: Verificar versión de Maven
        run: mvn -v