name: ejecuta mi action con docker

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ['arc-normaliza-runner-set']
    env:
      DOCKERHUB_USER: jeanedwien            
      DOCKERHUB_TOKEN: dckr_pat_i9ZRM2ElK8an5jO7w7BaKAaa440
      IMAGE_NAME: miapp                     
      IMAGE_TAG: latest  
    steps:
      - name: 🧹 Checkout del repositorio
        uses: actions/checkout@v4

      - name: 🧩 Validar Azure CLI
        run: |
          echo "🔹 Versión de Azure CLI:"
          az version
          echo "🔹 Autenticando con Azure (modo dry-run):"
          az cloud list --output table
          echo "✅ Azure CLI disponible y funcional."

      - name: Log in to Docker Hub
        run: |
          echo "$DOCKERHUB_TOKEN" | docker login docker.io -u "$DOCKERHUB_USER" --password-stdin

      - name: Instalar Java 17 con cache de Maven
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          # cache: 'maven'

      - name: hola actions
        uses: edwien-dev/central_devops/.github/actions/maven@main
        with:
          nombre: "jean edwien"

      - name: Build Docker image
        run: |
          docker build -t $DOCKERHUB_USER/$IMAGE_NAME:$IMAGE_TAG .

      - name: Push Docker image
        run: |
          docker push $DOCKERHUB_USER/$IMAGE_NAME:$IMAGE_TAG